# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170302_1545'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='traveler',
            field=models.ManyToManyField(related_name='User_trips', to='users.User'),
        ),
    ]
