# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170302_1545'),
        ('trips', '0002_trip_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='users.User'),
            preserve_default=False,
        ),
    ]
